### ISSUE TITLE
request help: Provide a configuration to disable ipv6

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#6017]
### Issue description

When APISIX parses the upstream host, it may be parsed as `ipv6` or `ipv4`. 
Hope to provide a configuration in `config.yaml` to have the ability to disable `ipv6`.

### Environment

- apisix version (cmd: `apisix version`): master
- OS (cmd: `uname -a`): centos 7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.*
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.14
- apisix-dashboard version, if have: - 
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner): -
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): -

**Comment by leslie-tsang** [comment]
Like [enable_ipv6](https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L35) ?

**Comment by leslie-tsang** [comment]
```patch
diff --git a/apisix/cli/ngx_tpl.lua b/apisix/cli/ngx_tpl.lua
index b3fd0d6e..9655723b 100644
--- a/apisix/cli/ngx_tpl.lua
+++ b/apisix/cli/ngx_tpl.lua
@@ -248,7 +248,7 @@ http {
 
     lua_socket_log_errors off;
 
-    resolver {% for _, dns_addr in ipairs(dns_resolver or {}) do %} {*dns_addr*} {% end %} {% if dns_resolver_valid then %} valid={*dns_resolver_valid*}{% end %};
+    resolver {% for _, dns_addr in ipairs(dns_resolver or {}) do %} {*dns_addr*} {% end %} {% if dns_resolver_valid then %} valid={*dns_resolver_valid*}{% end %} ipv6={% if enable_ipv6 then %}on{% else %}off{% end %};
     resolver_timeout {*resolver_timeout*};
 
     lua_http10_buffering off;
```
Might this solve the problem ?

**Comment by haoxins** [comment]
I'm not sure `enable_ipv6` is a good naming for this case, `enable_ipv6` is a bit general.
Maybe `dns_resolver_disable_ipv6` is better?

---

If we can get an agreement, I think I can help to implement and test the change.

**Comment by spacewander** [comment]
@haoxins 
Thanks for your attention! However,
@leslie-tsang 
Could you link your PR to this issue so that people know you are working on it?

**Comment by chenyyyang** [comment]
![image](https://user-images.githubusercontent.com/22273370/199198524-7c035069-5727-40d1-a69a-ab88c014c54b.png)
Hi @spacewander  @leslie-tsang 
i have set   enable_ipv6: false in my config-default.yaml
but it seem not work in my case.
When i tried to use "resty.http" lib to call an internal domain in company network, the return address is IPv6 which is not able to send http request .
Meanwhile, "curl " and "ping" command could get the correct address.
Could you mind giving me some advice?Thanks

**Comment by tzssangglass** [comment]
> i have set enable_ipv6: false in my config-default.yaml
> but it seem not work in my case.
> When i tried to use "resty.http" lib to call an internal domain in company network, the return address is IPv6 which is not able to send http request .
> Meanwhile, "curl " and "ping" command could get the correct address.
> Could you mind giving me some advice?Thanks

which version of APISIX did you use? This should be fixed by: #6023

**Comment by tzssangglass** [comment]
> i have set enable_ipv6: false in my config-default.yaml
> but it seem not work in my case.
> When i tried to use "resty.http" lib to call an internal domain in company network, the return address is IPv6 which is not able to send http request .

which version of APISIX did you use?

**Comment by chenyyyang** [comment]
ARG APISIX_VERSION=2.11.0
later, i tried to set this to false, then can receive ipv4 result.But  error still occurs
![image](https://user-images.githubusercontent.com/22273370/199433335-7c42ac87-ac51-4188-80da-f1cab09c276e.png)
